# Generated by Django 5.2.1 on 2025-06-16 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerprofile',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pno', models.CharField(max_length=50)),
                ('add', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='customer_profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
