# Generated by Django 5.2.1 on 2025-06-11 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('seller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=50, unique=True)),
                ('add', models.CharField(max_length=50)),
                ('gstno', models.CharField(max_length=50, unique=True)),
                ('seller_photo', models.ImageField(upload_to='seller_photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
