# Generated by Django 5.2.1 on 2025-06-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_sellerprofile_user_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Zebronics', 'Zebronics'), ('Boat', 'Boat'), ('Sony', 'Sony'), ('Allen Solly', 'Allen Solly'), ('H&M', 'H&M'), ('Peter England', 'Peter England'), ('Denim', 'Denim')], default='Boat', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Mens collection', 'Mens collection'), ('Womens collection', 'Womens collection'), ('Kids collection', 'Kids collection')], default='Electronics', max_length=50),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
